# Generated by Django 3.0.3 on 2020-11-04 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(default='', verbose_name='Descripción')),
                ('iva', models.CharField(default=13, max_length=2, verbose_name='IVA')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio')),
                ('opciones', models.TextField(default='', verbose_name='Opciones')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoIdentificacion', models.CharField(default='', max_length=1, verbose_name='Tipo identificacion')),
                ('identificacion', models.CharField(default='', max_length=15, verbose_name='Identificación')),
                ('telefono', models.CharField(default='', max_length=15, verbose_name='Teléfono')),
                ('pais', models.CharField(default=0, max_length=2, verbose_name='País')),
                ('provincia', models.CharField(default=0, max_length=4, verbose_name='Provincia')),
                ('canton', models.CharField(default=0, max_length=4, verbose_name='Canton')),
                ('distrito', models.CharField(default=0, max_length=4, verbose_name='Distrito')),
                ('barrio', models.CharField(default=0, max_length=4, verbose_name='Barrio')),
                ('direccion', models.TextField(default='', verbose_name='Dirección')),
                ('idplan', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='coreAdmin.Plan', verbose_name='Plan')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
