# Generated by Django 3.0.3 on 2020-11-04 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='idplan',
        ),
    ]
