# Generated by Django 3.0.3 on 2020-11-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreAdmin', '0003_auto_20201103_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='barrio',
            field=models.CharField(default=0, max_length=4, verbose_name='Barrio'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='canton',
            field=models.CharField(default=0, max_length=4, verbose_name='Canton'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='distrito',
            field=models.CharField(default=0, max_length=4, verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='pais',
            field=models.CharField(default=0, max_length=2, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='provincia',
            field=models.CharField(default=0, max_length=4, verbose_name='Provincia'),
        ),
    ]
