# Generated by Django 3.1.3 on 2020-12-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreAdmin', '0004_auto_20201103_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(max_length=100, verbose_name='Identificador del parametro')),
                ('valor', models.CharField(max_length=100, verbose_name='Valor del parametro')),
                ('detalle', models.CharField(default='', max_length=100, verbose_name='Detalle del parametro')),
            ],
        ),
    ]
