# Generated by Django 3.0.3 on 2021-01-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreAdmin', '0005_parametro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Identificador del parametro')),
                ('descripcion', models.TextField(default='', verbose_name='Descripción')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
            ],
        ),
    ]
