# Generated by Django 3.1.3 on 2021-03-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreAdmin', '0006_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='primerIngreso',
            field=models.BooleanField(default=False, verbose_name='Ha ingresado'),
        ),
    ]
