# Generated by Django 3.0.3 on 2020-10-09 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.CharField(max_length=100, verbose_name='Nombre corto')),
                ('eslogan', models.CharField(default='', max_length=200, verbose_name='Eslogan del comercio')),
                ('descripcion', models.TextField(default='', verbose_name='Descripción')),
                ('redessociales', models.TextField(default='[]', verbose_name='Redes Sociales')),
                ('contacto', models.TextField(default='[]', verbose_name='Contácto')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dueño')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(default='', verbose_name='Descripción')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('moneda', models.IntegerField(default=0, verbose_name='Moneda')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio')),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreComercios.Comercio', verbose_name='Comercio')),
            ],
        ),
    ]
