# Generated by Django 3.0.3 on 2020-10-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='contacto',
            field=models.TextField(verbose_name='Contácto'),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='redessociales',
            field=models.TextField(verbose_name='Redes Sociales'),
        ),
    ]
