# Generated by Django 3.0.3 on 2020-10-13 14:17

import coreComercios.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0002_auto_20201008_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='img_acercade',
            field=models.ImageField(blank=True, null=True, upload_to=coreComercios.models.custom_upload_Comercio, verbose_name='Imagen de acerca de'),
        ),
        migrations.AddField(
            model_name='comercio',
            name='img_superior',
            field=models.ImageField(blank=True, null=True, upload_to=coreComercios.models.custom_upload_Comercio, verbose_name='Imagen superior'),
        ),
        migrations.CreateModel(
            name='ImagenesProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=coreComercios.models.custom_upload_Producto, verbose_name='Imagen del producto')),
                ('principal', models.BooleanField(default=False, verbose_name='Imagen principal')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreComercios.Producto', verbose_name='Producto asociado')),
            ],
        ),
    ]
