# Generated by Django 3.0.3 on 2020-10-13 14:34

import coreComercios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0003_auto_20201013_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='img_acercade',
            field=models.ImageField(default='comercios/noimageAbout.jpg', upload_to=coreComercios.models.custom_upload_Comercio, verbose_name='Imagen de acerca de'),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='img_superior',
            field=models.ImageField(default='comercios/noimageSup.jpg', upload_to=coreComercios.models.custom_upload_ComercioSup, verbose_name='Imagen superior'),
        ),
        migrations.AlterField(
            model_name='imagenesproducto',
            name='imagen',
            field=models.ImageField(default='productos/noimageProd.jpg', upload_to=coreComercios.models.custom_upload_Producto, verbose_name='Imagen del producto'),
        ),
    ]
