# Generated by Django 3.0.3 on 2020-10-13 15:07

import coreComercios.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0004_auto_20201013_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='img_acercade',
            field=django_resized.forms.ResizedImageField(crop=None, default='comercios/noimageAbout.jpg', force_format=None, keep_meta=True, quality=0, size=[500, 433], upload_to=coreComercios.models.custom_upload_Comercio, verbose_name='Imagen de acerca de'),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='img_superior',
            field=django_resized.forms.ResizedImageField(crop=None, default='comercios/noimageSup.jpg', force_format=None, keep_meta=True, quality=0, size=[900, 600], upload_to=coreComercios.models.custom_upload_ComercioSup, verbose_name='Imagen superior'),
        ),
    ]
