# Generated by Django 3.0.3 on 2020-10-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0006_auto_20201013_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='slug',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre corto'),
        ),
    ]
