# Generated by Django 3.0.3 on 2020-11-04 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreAdmin', '0002_remove_perfil_idplan'),
        ('coreComercios', '0014_auto_20201103_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='idplan',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreAdmin.Plan', verbose_name='Plan'),
        ),
    ]
