# Generated by Django 3.0.3 on 2020-11-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0023_remove_comercio_idplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='idplan',
            field=models.CharField(blank=True, default=False, max_length=2, null=True, verbose_name='Plan'),
        ),
    ]
