# Generated by Django 3.0.3 on 2020-11-04 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0025_auto_20201103_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comercio',
            name='idplan',
        ),
    ]
