# Generated by Django 3.0.3 on 2020-11-04 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreAdmin', '0004_auto_20201103_2221'),
        ('coreComercios', '0026_remove_comercio_idplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='idplan',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='coreAdmin.Plan', verbose_name='Plan'),
        ),
    ]
