# Generated by Django 3.0.3 on 2020-11-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0029_remove_comercio_idplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='idplan',
            field=models.CharField(default='0', max_length=2, verbose_name='Plan'),
        ),
    ]
