# Generated by Django 3.1.3 on 2020-11-25 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0030_comercio_idplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreComercios.comercio', verbose_name='Comercio')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='colecciones',
            field=models.ManyToManyField(blank=True, null=True, to='coreComercios.Coleccion', verbose_name='Colecciones'),
        ),
    ]
