# Generated by Django 3.1.3 on 2020-12-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0031_auto_20201125_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='colecciones',
            field=models.ManyToManyField(blank=True, to='coreComercios.Coleccion', verbose_name='Colecciones'),
        ),
    ]
