# Generated by Django 3.1.3 on 2021-01-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0032_auto_20201203_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='idplan',
            field=models.IntegerField(default='0', max_length=2, verbose_name='Plan'),
        ),
    ]
