# Generated by Django 3.1.3 on 2021-01-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0033_auto_20210104_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='idplan',
            field=models.IntegerField(default='0', verbose_name='Plan'),
        ),
    ]
