# Generated by Django 3.1.3 on 2021-01-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0034_auto_20210104_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='visualizaciones',
            field=models.IntegerField(default='0', verbose_name='Visualizaciones'),
        ),
    ]
