# Generated by Django 3.1.3 on 2021-01-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0035_comercio_visualizaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comercio',
            name='visualizaciones',
        ),
        migrations.AddField(
            model_name='producto',
            name='visualizaciones',
            field=models.IntegerField(default='0', verbose_name='Visualizaciones'),
        ),
    ]
