# Generated by Django 3.1.3 on 2021-02-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0036_auto_20210109_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='fechaVencimiento',
            field=models.DateField(default='', null=True, verbose_name='Plan'),
        ),
    ]
