# Generated by Django 3.1.3 on 2021-02-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0037_comercio_fechavencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='fechaVencimiento',
            field=models.DateField(null=True, verbose_name='Plan'),
        ),
    ]
