# Generated by Django 3.1.3 on 2021-02-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0039_auto_20210211_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='fechaVencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha vencimiento'),
        ),
    ]
