# Generated by Django 3.1.3 on 2021-02-12 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0040_auto_20210211_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comercio',
            name='fechaVencimiento',
        ),
    ]
