# Generated by Django 3.1.3 on 2021-02-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0041_remove_comercio_fechavencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='fechaVencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha vencimiento'),
        ),
    ]
