# Generated by Django 3.1.3 on 2021-02-15 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreAdmin', '0006_faq'),
        ('ipn', '0008_auto_20181128_1032'),
        ('coreComercios', '0042_comercio_fechavencimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenesComercios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRealizado', models.DateField(auto_now_add=True, verbose_name='Fecha realizado')),
                ('fechaVencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha vencimiento')),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreComercios.comercio', verbose_name='Comercio asociado')),
                ('ipn', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ipn.paypalipn', verbose_name='Paypal Ipn')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreAdmin.plan', verbose_name='Plan seleccionado')),
            ],
        ),
    ]
