# Generated by Django 3.1.3 on 2021-03-21 00:52

import coreComercios.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0043_ordenescomercios'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='logo',
            field=django_resized.forms.ResizedImageField(crop=None, default='comercios/noimage.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[500, 500], upload_to=coreComercios.models.custom_upload_ComercioLogo, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='img_acercade',
            field=django_resized.forms.ResizedImageField(crop=None, default='comercios/noimage.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[500, 433], upload_to=coreComercios.models.custom_upload_Comercio, verbose_name='Imagen de acerca de'),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='img_superior',
            field=django_resized.forms.ResizedImageField(crop=None, default='comercios/noimage.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[900, 600], upload_to=coreComercios.models.custom_upload_ComercioSup, verbose_name='Imagen superior'),
        ),
        migrations.AlterField(
            model_name='imagenesproducto',
            name='imagen',
            field=django_resized.forms.ResizedImageField(crop=None, default='productos/noimage.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[600, 600], upload_to=coreComercios.models.custom_upload_Producto, verbose_name='Imagen del producto'),
        ),
    ]
