# Generated by Django 3.1.3 on 2021-03-21 01:22

import coreComercios.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0044_auto_20210320_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='logo',
            field=django_resized.forms.ResizedImageField(crop=None, default='comercios/noimage.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[500, 433], upload_to=coreComercios.models.custom_upload_ComercioLogo, verbose_name='Logo'),
        ),
    ]
