# Generated by Django 3.1.3 on 2021-03-21 03:05

import coreComercios.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0045_auto_20210320_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='favicon',
            field=django_resized.forms.ResizedImageField(crop=None, default='comercios/noimage.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[500, 500], upload_to=coreComercios.models.custom_upload_ComercioFavicon, verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='logo',
            field=django_resized.forms.ResizedImageField(crop=None, default='comercios/noimage.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[500, 500], upload_to=coreComercios.models.custom_upload_ComercioLogo, verbose_name='Logo'),
        ),
    ]
