# Generated by Django 3.1.3 on 2021-04-01 17:08

import coreComercios.models
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0046_auto_20210320_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='favicon',
            field=django_resized.forms.ResizedImageField(crop=None, default='comercios/noimage.jpg', force_format='PNG', keep_meta=True, quality=75, size=[50, 50], upload_to=coreComercios.models.custom_upload_ComercioFavicon, verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='img_acercade',
            field=django_resized.forms.ResizedImageField(crop=None, default='comercios/noimage.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[900, 600], upload_to=coreComercios.models.custom_upload_Comercio, verbose_name='Imagen de acerca de'),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='img_superior',
            field=django_resized.forms.ResizedImageField(crop=None, default='comercios/noimage.jpg', force_format='JPEG', keep_meta=True, quality=100, size=[900, 600], upload_to=coreComercios.models.custom_upload_ComercioSup, verbose_name='Imagen superior'),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='logo',
            field=django_resized.forms.ResizedImageField(crop=None, default='comercios/noimage.jpg', force_format='PNG', keep_meta=True, quality=75, size=[400, 144], upload_to=coreComercios.models.custom_upload_ComercioLogo, verbose_name='Logo'),
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=35, verbose_name='Título')),
                ('subtitulo', models.CharField(max_length=35, verbose_name='Sub título')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('boton', models.CharField(max_length=15, verbose_name='Texto Botón')),
                ('url', models.CharField(max_length=150, verbose_name='URL del botón')),
                ('imagen', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=75, size=[1920, 800], upload_to=coreComercios.models.custom_upload_slider, verbose_name='Imagen')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreComercios.comercio', verbose_name='Comercio')),
            ],
        ),
    ]
