# Generated by Django 3.1.3 on 2021-04-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0047_auto_20210401_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='target',
            field=models.BooleanField(default=False, verbose_name='Nueva ventana'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripción'),
        ),
    ]
