# Generated by Django 3.1.3 on 2021-04-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0048_auto_20210401_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='boton',
            field=models.CharField(max_length=15, verbose_name='Texto del Botón'),
        ),
    ]
