# Generated by Django 3.1.3 on 2021-04-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0049_auto_20210401_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='ajustes',
            field=models.TextField(default='{}', verbose_name='Otros ajustes'),
        ),
    ]
