# Generated by Django 3.1.3 on 2021-06-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0050_comercio_ajustes'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.BooleanField(default=False, verbose_name='Posee inventario'),
        ),
    ]
