# Generated by Django 3.1.3 on 2021-06-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreComercios', '0051_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='inventario',
            field=models.IntegerField(default='0', verbose_name='Cantidad de inventario'),
        ),
    ]
